models:
  - name: gold_activities
    description: "business-ready activities data"
    tests: []

  - name: gold_opportunities
    description: "business-ready opportunities data"
    tests: []

  - name: gold_sales_reps
    description: "business-ready sales reps data"
    tests: []
