models:
  - name: bronze_activities
    description: "raw activities data"
    columns:
      - name: activity_id
        tests:
          - unique
      - name: activity_type
        tests:
          - not_null
      - name: outcome
        tests:
          - not_null

  - name: bronze_opportunity
    description: "raw opportunity data"
    columns:
      - name: opportunity_id
        tests:
          - unique
      - name: account_name
        tests:
          - not_null
      - name: product_type
        tests:
          - not_null
      - name: stage
        tests:
          - not_null
      - name: opportunity_value
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "opportunity_value > 0"

  - name: bronze_sales_reps
    description: "raw sales reps data"
    columns:
      - name: rep_id
        tests:
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: quota
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "quota > 0"


                    