version: 2
sources:
  - name: RAW_GROUP_3_DBT_CLASS
    database: RAW_BUSINESS_DATA
    schema: GROUP_3_SALES
    tables:
      - name: ACTIVITIES
      - name: OPPORTUNITIES
      - name: SALES_REPS